"""add_license_key_and_merchant_id_columns

Revision ID: 2b3a006cbbfa
Revises: 
Create Date: 2026-03-31 16:50:12.400202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3a006cbbfa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'TRANSACTION', 'ENROLLMENT', 'DEVICE_AUTH', 'DEVICE_BLOCK', 'OTA_UPDATE', 'CONFIG_CHANGE', name='auditaction'), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firmware_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('is_stable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.add_column('customers', sa.Column('merchant_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'customers', 'merchants', ['merchant_id'], ['id'])
    # Add license_key as nullable first, then backfill existing rows, then set NOT NULL
    op.add_column('devices', sa.Column('license_key', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('device_serial_number', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('device_model', sa.String(length=100), nullable=True))
    # Backfill existing devices with a placeholder license_key based on their id
    op.execute("UPDATE devices SET license_key = 'LEGACY-' || id WHERE license_key IS NULL")
    op.alter_column('devices', 'license_key', nullable=False)
    op.create_unique_constraint('uq_devices_license_key', 'devices', ['license_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_devices_license_key', 'devices', type_='unique')
    op.drop_column('devices', 'device_model')
    op.drop_column('devices', 'device_serial_number')
    op.drop_column('devices', 'license_key')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'merchant_id')
    op.drop_table('firmware_versions')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
